start = a:(<'a'>) ('b' &{ pvImplImmediateVar($a) = "a" })

@{
Private Function pvImplImmediateVar(ByVal lIndex As Long) As String
    Dim lIdx            As Long
    
    With ctx
        For lIdx = .ThunkPos - 1 To 0 Step -1
            With .ThunkData(lIdx)
                If .Action = ucsActVarSet Then
                    If .CaptureBegin = lIndex Then
                        Exit For
                    End If
                End If
            End With
        Next
        For lIdx = lIdx - 1 To 0 Step -1
            With .ThunkData(lIdx)
                If .Action = ucsActResultSet Then
                    pvImplImmediateVar = Mid$(ctx.Contents, .CaptureBegin + 1, .CaptureEnd - .CaptureBegin)
                    Exit For
                End If
            End With
        Next
    End With
End Function
}